web: cd apps && streamlit run app_deploy.py --server.port=$PORT --server.address=0.0.0.0
      - key: ENVIRONMENT
        value: deployment
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false 
